### ISSUE TITLE
Max output

### ISSUE THREAD

**Issue by Staegrin** [ProspectPyxis/CustomCapacitors#4]
So after doing some testing I think I found an error.

Made a capacitor that can hold 50 000 000 -> made the max output rate 1 000 000 

let that capacitor fill with 500 000 to 1 200 000 and connect a basic thermal expansion energy cell that has a max 10 000 input acceptance. 

The custom capacitor will dump all its power immediately. So while the capacitor will output a 1 000 000 FE the cell will only accept 10 000 and the remaining 990 000 will be lost.

**Comment by ProspectPyxis** [comment]
Fixed in 1.1.1.

**Comment by ProspectPyxis** [comment]
Well, this is embarassing - the way I fixed this issue means that I've created the opposite bug, where all capacitors essentially act as infinite energy sources. It's fixed in the next update, but it'll also be a pretty large content update coming up, so this might take a short while to get fixed. Until then, I'm reopening this issue as a reminder.

**Comment by ProspectPyxis** [comment]
Whoops, this bug was actually also fixed in 1.2.0, I just forgot to close this. Doing that now.
